services:
  http-api:
    build: ./http-api
    ports:
      - "3000:3000"
    volumes:
      - ./http-api/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000

  users:
    build: ./microservices/users
    volumes:
      - ./microservices/users/src:/usr/src/app/src
    command: npm run start:dev
