services:
  http-api:
    build: ./http-api
    ports:
      - "3000:3000"
    volumes:
      - ./http-api/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000

  nats:
    image: nats
    ports:
      - 4222:4222

  users_microservice:
    build: ./microservices/users
    volumes:
      - ./microservices/users/src:/usr/src/app/src
    command: npm run start:dev

  payments_microservice:
    build: ./microservices/payments
    volumes:
      - ./microservices/payments/src:/usr/src/app/src
    command: npm run start:dev
